basePath: /api
definitions:
  model.Social:
    properties:
      css_class:
        type: string
      handle:
        type: string
      id:
        type: string
      media_type:
        type: string
      metadata:
        additionalProperties: true
        type: object
      name:
        type: string
      order:
        type: integer
      src:
        type: string
      type:
        type: string
      url:
        type: string
    type: object
  model.Technology:
    properties:
      css_class:
        type: string
      id:
        type: string
      media_type:
        type: string
      metadata:
        additionalProperties: true
        type: object
      name:
        type: string
      order:
        type: integer
      src:
        type: string
      type:
        type: string
      url:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: contact@gaurav.dev
    url: http://gaurav.dev
  description: API for portfolio website managing blogs, experiences, technologies,
    and more
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://gaurav.dev/
  title: Portfolio API
  version: "1.0"
paths:
  /socials:
    get:
      consumes:
      - application/json
      description: Get all social media links
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Social'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get socials
  /technologies:
    get:
      consumes:
      - application/json
      description: Get all technologies sorted by order
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Technology'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get technologies
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
