name: Docker

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Azure SDK takes forever (~10 mins) to build, saving some build time till it's faster
      # - name: Install Go - This is just for failing fast
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.18
      # - name: Install enumer and run go:generate
      #   run: |
      #     go install github.com/dmarkham/enumer@latest
      #     go generate ./...
      # - name: Build the server
      #   run: go build server.go
      - name: Install Node - This is just for failing fast
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build the UI
        run: |
          npm install --location=global npm
          npx browserslist@latest --update-db
          npm install
          npm run build
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Log in to the GHCR
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_PAT }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push container image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy the image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          # Sometimes you gotta bear the burden of working with rootful containers (:
          script: |
            set +o history
            sudo podman stop ${{ secrets.CONTAINER_NAME }} && sudo podman rm ${{ secrets.CONTAINER_NAME }}
            sudo podman pull ${{ steps.meta.outputs.tags }}
            sudo podman run -d -p ${{ secrets.CONTAINER_EXTERNAL_PORT }}:${{ secrets.CONTAINER_INTERNAL_PORT }} \
              -e GIN_MODE="${{ secrets.CONTAINER_GIN_MODE }}" \
              -e KEEP_ALIVE_CRON="${{ secrets.CONTAINER_KEEP_ALIVE_CRON }}" \
              -e KEEP_ALIVE_BASE_URL="${{ secrets.CONTAINER_KEEP_ALIVE_BASE_URL }}" \
              -e APP_AUTH="${{ secrets.CONTAINER_APP_AUTH }}" \
              -e MONGO_URI="${{ secrets.CONTAINER_MONGO_URI }}" \
              -e MS_CLIENT_ID="${{ secrets.CONTAINER_MS_CLIENT_ID }}" \
              -e MS_EMAIL_KEY="${{ secrets.CONTAINER_MS_EMAIL_KEY }}" \
              -e MS_GRAPH_SELF_USER_ID="${{ secrets.CONTAINER_MS_GRAPH_SELF_USER_ID }}" \
              -e MS_SECRET_ID="${{ secrets.CONTAINER_MS_SECRET_ID }}" \
              -e MS_TENANT_ID="${{ secrets.CONTAINER_MS_TENANT_ID }}" \
              -e SELF_EMAIL="${{ secrets.CONTAINER_SELF_EMAIL }}" \
              -e PORT="${{ secrets.CONTAINER_INTERNAL_PORT }}" \
              --name "${{ secrets.CONTAINER_NAME }}" \
              ${{ steps.meta.outputs.tags }}
            set -o history
      - name: Check service health
        uses: jtalk/url-health-check-action@v2
        with:
          url: http://${{ secrets.SSH_HOST }}/health
          follow-redirect: false
          max-attempts: 5
          retry-delay: 5s
          retry-all: false

